config/routes.rb
Rails.application.routes.draw do
	
	
	resources :businesses
	resources :categories
	
	get 'search' => 'businesses#search'
  get 'login' => 'application#set_session_pass'
	
	root 'businesses#index'
	

end

app/models/business.rb
class Business < ActiveRecord::Base
	to_param :name
	validates :name, uniqueness: true
	validates :name, :phone, :category, presence: true
	validates :phone, :fax, format: {with: /\A\([0-9]{3}\) [0-9]{3}-[0-9]{4}\z/,
		message: 'number must be in the form (123) 456-7890',
		allow_blank: true
	}
	validates :description, :image, presence: true, if: :premium?
	belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	to_param :name
	validates :name, uniqueness: true
    has_many :businesses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_pass

	def set_session_pass
		session[:password] = params[:pass]
		if session[:password] == ENV["ADMIN_PASS"].presence || false
			flash[:success] = "Login successful!"
		end
		redirect_back(fallback_location: root_path)
	end
	
	private
	def set_pass
		@ADMIN_PASS = ENV["ADMIN_PASS"].presence || false
	end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
	before_action :check_admin!, except: [ :index, :show, :search ]

	#TODO: Rename business => listing?
	def index
		@businesses = Business.order(:name)
	end
	
	def show
		@business = Business.find(params[:id])
	end
	
	def new
		@business = Business.new
	end
	
	def edit
		@business = Business.find(params[:id])
	end
	
	def create
		@business = Business.new(business_params)
		
		if @business.save
			redirect_to @business
		else
			render 'new'
		end
	end
	
	def update
		@business = Business.find(params[:id])
		
		if @business.update(business_params)
			redirect_to @business
		else
			render 'edit'
		end
	end
	
	def destroy
		@business = Business.find(params[:id])
		@business.destroy
		
		redirect_to businesses_path
	end
	
	def search
		@businesses = Business.where(['name ILIKE ? OR description ILIKE ?'] + ['%' + params[:q] + '%']*2)\
		| (Category.where('name ILIKE ?', '%' + params[:q] + '%').map {|cat| cat.businesses}).flatten  # Union of sets
	end
	
	private
		def business_params
			params.require(:business).permit(:name, :address, :phone, :fax, :website, :premium, :image, :description, :hours, :reservation, :category_id)
		end

		def check_admin!
			unless session[:password] == @ADMIN_PASS
				redirect_to businesses_path
				flash[:error] = "You're not logged in"
				return false
			end
		end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :check_admin!, except: [ :index, :show ]

	def index
		@categories = Category.order(:name)
	end
	
	def show
		@category = Category.find(params[:id])
	end
	
	def new
		@category = Category.new
	end
	
	def edit
		@category = Category.find(params[:id])
	end
	
	def create
		@category = Category.new(category_params)
		
		if @category.save
			redirect_to @category
		else
			render 'new'
		end
	end
	
	def update
		@category = Category.find(params[:id])
		
		if @category.update(category_params)
			redirect_to @category
		else
			render 'edit'
		end
	end
	
	private
		def category_params
			params.require(:category).permit(:name, :image)
		end

		def check_admin!
			unless session[:password] == @ADMIN_PASS
				redirect_to categories_path
				flash[:error] = "You're not logged in'"
				return false
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/businesses/_business.html.erb
<%= link_to business_path(business) do %>
<div class="business card">
	<h2><%= business.name %></h2>
	<% if business.premium? %>
		<%= image_tag business.image %>
		<p class="description"><%= business.description %></p>
	<% end %>
	<% if business.address? %>
		<h5><%= business.address %> | <%= business.phone %></h5>
	<% else %>
		<h4><%= business.phone %></h4>
	<% end %>
</div>
<% end %>

app/views/businesses/_form.html.erb
<%= form_for @business do |f| %>
	<% if @business.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@business.errors.count, "error") %> prohibited
			this listing from being saved:</h2>
			<ul>
				<% @business.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<fieldset>
		<h3>Basic Features</h3>
		<p>
			<%= f.label :name %><br>
			<%= f.text_field :name %>
		</p>
		<p>
			<%= f.label :address %><br>
			<%= f.text_field :address %>
		</p>
		<p>
			<%= f.label :phone %><br>
			<%= f.telephone_field :phone %>
		</p>
		<p>
			<%= f.label :fax %><br>
			<%= f.telephone_field :fax %>
		</p>
		<p>
			<%= f.label :website %><br>
			<%= f.url_field :website %>
		</p>
	</fieldset>
	<fieldset>
		<h3>Premium Features</h3>
		<p>
			<%= f.label :premium, 'Premium listing?' %>
			<%= f.check_box :premium %>
		</p>
		<p>
			<%= f.label :image %><br>
			<%= f.url_field :image %>
		</p>
		<p>
			<%= f.label :description %><br>
			<%= f.text_area :description %>
		</p>
		<p>
			<%= f.label :hours %><br>
			<%= f.text_area :hours %>
		</p>
		<p>
			<%= f.label :reservation, 'Reservation embed code' %><br>
			<%= f.text_area :reservation %>
		</p>
	</fieldset>
	<p>
		<%= f.label :category_id %><br>
		<%= f.select(:category_id, options_from_collection_for_select(Category.all, :id, :name, params[:category_id] || @business.category_id), prompt: 'Select a category...') %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing "<%= Business.find(params[:id]).name %>"</h1>
<% content_for :title do %>Editing listing<% end %>

<%= render 'form' %>

app/views/businesses/index.html.erb
<h1>Businesses</h1>
<% content_for :title do %>Businesses<% end %>

<p>Here is a list of all <%= @businesses.length %> Lexington businesses in the directory.</p>

<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search listings:") %>
  <%= text_field_tag(:q) %>
  <!--<%= search_field(:business, :name) %>-->
  <%= submit_tag("Search") %>
<% end %>
<% if session[:password] == @ADMIN_PASS %>
  <%= link_to 'Add business listing', new_business_path %>
<% end %>
<br><br>
<div id="wrapper">
	<%= render @businesses %>
</div>

app/views/businesses/new.html.erb
<h1>New listing</h1>
<% content_for :title do %>New listing<% end %>

<%= render 'form' %>

app/views/businesses/search.html.erb
<h1>Businesses</h1>
<% content_for :title do %>Businesses<% end %>
<% num_results = @businesses.length %>
<% case num_results %>
  <% when 0 %>
  <p>There were no results.</p>
  <% when 1 %>
  <% controller.redirect_to @businesses.first %>
  <% else %>
  <p>Here are your <%= num_results %> search results.</p>
<% end %>

<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search listings:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

<br><br>
<div id="wrapper">
	<%= render @businesses %>
</div>

app/views/businesses/show.html.erb
<h1><%= @business.name %></h1>
<% content_for :title do %><%= @business.name %><% end %>

<% if session[:password] == @ADMIN_PASS %>
	<%= link_to 'Edit', edit_business_path %> |
	<%= link_to 'Delete', business_path,
		method: :delete,
		data: {confirm: 'Are you sure you want to delete this listing?'} %>
	<br>
<% end %>

<% if @business.premium? %>
	<%= image_tag @business.image, width: 500 %>
<% end %>
<div id="details">
	<% if @business.description? %>
		<p><%= @business.description %></p>
	<% end %>
	<% if @business.premium? && @business.hours? %>
		<%= simple_format(@business.hours) %>
	<% end %>
	<% if @business.address? %>
		<p>Location: <%= @business.address %></p>
	<% end %>
	<p>Phone: <%= @business.phone %></p>
	<% if @business.fax? %>
		<p>Fax: <%= @business.fax %></p>
	<% end %>
	<% if @business.website? %>
		<p><%= link_to "Website", @business.website %></p>
	<% end %>
	<% if @business.premium? && @business.reservation? %>
		<%= @business.reservation.html_safe %><br>
	<% end %>
	<% if @business.address? %>
		<iframe width="600" height="450" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCNCZ0Twm_HFRaZ5i-FuPDYs3rLwm4_848&q=<%= @business.address %>, Lexington MA"></iframe>
	<% end %>
</div>
<hr>
Category: <%= link_to @business.category.name, category_path(@business.category) %>

app/views/categories/_category.html.erb
<%= link_to category_path(category) do %>
<div class="category card">
	<h2><%= category.name %><span class="count"> (<%= category.businesses.length %>)</span></h2>
	<% if category.image? %>
		<%= image_tag category.image %>
	<% end %>
</div>
<% end %>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
	<% if @category.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@category.errors.count, "error") %> prohibited
			this category from being saved:</h2>
			<ul>
				<% @category.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :image %><br>
		<%= f.url_field :image %>
	</p>
		<%= f.submit %>
	</p>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing "<%= Category.find(params[:id]).name %>"</h1>
<% content_for :title do %>Editing category<% end %>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<% content_for :title do %>Categories<% end %>
<% if session[:password] == @ADMIN_PASS %>
	<%= link_to 'Add category', new_category_path %>
<% end %>
<br><br>
<div id="wrapper">
<%= render @categories %>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>
<% content_for :title do %>New category<% end %>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<% content_for :title do %><%= @category.name %><% end %>
<% if session[:password] == @ADMIN_PASS %>
	<%= link_to 'Edit category', edit_category_path %> |
	<%= link_to 'Delete category', category_path,
		method: :delete,
		data: {confirm: 'Are you sure you want to delete this category?'} %>
	<br><br>
	<%= link_to 'Add business', new_business_path(category_id: @category.id) %>
<% end %>
<p>Displaying <%= @category.businesses.count %> businesses in category.</p>
<br>
<div id="wrapper">
	<%= render @category.businesses.order(:name) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title><%= yield :title %> | Lex.ma Directory</title>
	<meta charset="utf-8">
	<meta name="description" content="View a searchable directory of Lexington, MA businesses and organizations.">
	<meta name="author" content="Derik Kauffman">
	<meta name="zipcode" content="02420,02421">

	<meta name="mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="theme-color" content="#1f7cdb" />
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<%= stylesheet_link_tag    'application', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
<nav>
	<%= link_to 'Lex.ma', 'https://lex.ma' %>
	<%= link_to 'Businesses', root_path %>
	<%= link_to 'Categories', categories_path %>
</nav>

<%= yield %>

</body>
</html>